safe: true
markdown: kramdown
highlighter: rouge
permalink: /:title.html
relative_permalinks: false

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Quincy Chen
    # url:  http://example.com/
    company:
        name: YouInnov Inc.
        # url:  http://example.com/

fork_url: https://github.com/QuincyChen/jekyller
progress: true
line_numbers: true
